############ MID Config #############
# 扩散模型相关参数
# optimizer
lr: 0.0001
# dataset
# 这个是数量少的根据MGTCF来的，自己跑的版本，但是为什么性能会弱？因为样本多了取平均之后效果就好了？
# data_dir: /home/littlered/Documents/TC-Diffuser/TC-Diffuser/processed_data_noise_traj_inten_wind_gph_env
# 这个是TC-Diffuser给的版本
data_dir: /mnt/e/data/TC-Diffusion/processed_data_noise_traj_inten_wind_gph_env
  # the path with the directory with XXX.pkl
# Training Prarmeters:
diffnet: TransformerConcatLinear #TransformerConcatLinear
encoder_dim: 256
context_dim: 256
tf_layer: 3
epochs: 250
batch_size: 128
eval_batch_size: 256  #
seed: 123
eval_every: 10 #每30步 验证一次 #这里不确定？？？
# Testing
eval_at: 30 #测试采用的epoch 可以改
# False-train  True-test
eval_mode: True
# eval_mode: False
# set to "ddim" to enable fast sampling
sampling: ddpm
############### Trajectron++ Config #################
# 与处理1D时序数据编码器有关
# misc
conf: None
debug: False
preprocess_workers: 0
# model parameters
offline_scene_graph: yes
dynamic_edges: yes
edge_state_combine_method: sum
edge_influence_combine_method: attention
edge_addition_filter: [0.25, 0.5, 0.75, 1.0]
edge_removal_filter: [1.0, 0.0]
override_attention_radius: []
incl_robot_node: False
map_encoding: False
augment: True
node_freq_mult_train: False
node_freq_mult_eval: False
scene_freq_mult_train: False
scene_freq_mult_eval: False
scene_freq_mult_viz: False
no_edge_encoding: False
# Data Parameters:
device: cuda:1
eval_device: None
